### PR TITLE
State Selinon in related projects

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fireantology** [comment]
@ask shall I include this ?

**Comment by fridex** [comment]
This pull request is based on discussion I had with @ask on IRC.

**Comment by fireantology** [comment]
Thanks for the clarification, I will anyway double check, you got link to IRC logs ?

**Comment by fridex** [comment]
> you got link to IRC logs?

https://botbot.me/freenode/celery/2016-09-22/?msg=73408632&page=1

**Comment by fridex** [comment]
Forgotten merge button? :)

**Comment by auvipy** [comment]
No

**Comment by fridex** [comment]
@auvipy thanks for the review. Could you please point me to the docs section where this could fit?

**Comment by fridex** [comment]
Any chance to get this in if I put this into a different section?

**Pull request closed without merging**
